name: Download model

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: 3.9

      - name: install
        run: pip install -U "huggingface_hub[cli]"

      - name: Run a one-line script
        run: huggingface-cli login --token ${{ secrets.TOKEN }} --add-to-git-credential

      - name: Run a multi-line script
        run: |
          huggingface-cli download Salesforce/codegen-350M-mono
          huggingface-cli download gpt2

      - name: Commit and push changes
        run: |
          sudo git config user.name "auto-push"
          sudo git config user.email "auto-push@example.com"
          sudo git add .
          sudo git commit -m "auto push from ci" || echo "No changes to commit"
          sudo git push
